development:
  adapter: postgresql
  encoding: utf8
  database: tetranucleotide
  username: ryanmoore
  password: 1qazSE$
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: tetranucleotide_test
  username: ryanmoore
  password: 1qazSE$
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: tetranucleotide_production
  username: ryanmoore
  password: 1qazSE$
  host: localhost